### ISSUE TITLE
AppImage missing

### ISSUE THREAD

**Issue by probonopd** [taisei-project/taisei#102]
Is the AppImage for Linux available for download somewhere? Thanks.

**Comment by lachs0r** [comment]
We’ve decided to drop AppImage for good. The app bundle/common runtime approach does not work reliably enough in practice and probably never will because the Linux ecosystem is not a single monolithic organization, and it causes more headaches than it’s worth.
Sorry, but if someone runs a Linux distro we can’t support through OBS/AUR and they’re unable to build from source, I’ll just tell them to run the Windows executable through Wine, because that is a common runtime that actually works.

**Comment by probonopd** [comment]
Thanks for your answer. However Linux would be really in a sorry state if it was not possible to produce working application bundles. Luckily it is possible, as hundreds of working apps on https://appimage.github.io/apps/ show. Please let me know if some day you want to try it again. Tools are getting better and better all the time.

**Comment by CounterPillow** [comment]
![lol](https://user-images.githubusercontent.com/308818/34649997-a344fa9a-f3b9-11e7-8e01-3c6034e55b11.png)

:thinking:

**Comment by laochailan** [comment]
@probonopd We had pretty frustrating and difficult to debug problems with AppImage before and with our relatively small team (and lack of experience with it) it’s not really possible for us to provide confidently.
If somebody who is experienced turns up to bundle it, and it works, that contribution would be welcome.
