### ISSUE TITLE
Taisei v1.3 fails to build if fileno(3) is a macro

### ISSUE THREAD

**Issue by julianaito** [taisei-project/taisei#165]
Hi,

While building Taisei 1.3 (from the tar.xz submodules bundle) on OpenBSD/amd64 6.5-current, i have the following error: 

```
cc -Isrc/25a6634@@taisei@exe -Isrc -I../taisei-v1.3/src -Isubprojects/cglm/include -I../taisei-v1.3/subprojects/cglm/include -I../taisei-v1.3/subprojects/glad/include -I/usr/X11R6/include/freetype2 -I/usr/local/include/libpng16 -I/usr/local/include/SDL2 -I/usr/X11R6/include -I/usr/local/include -flto -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -std=c11 -O2 -D_REENTRANT -Wall -Wpedantic -Werror=assume -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Wabsolute-value -Wcast-align -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-pedantic -Wformat-security -Wgcc-compat -Wgnu -Wignored-qualifiers -Wimplicit-fallthrough -Winit-self -Wmissing-prototypes -Wno-long-long -Wno-missing-braces -Wno-typedef-redefinition -Wnull-dereference -Wparentheses -Wsometimes-uninitialized -Wstrict-prototypes -Wtype-limits -Wunneeded-internal-declaration -Wunreachable-code -Wunreachable-code-loop-increment -msse -mfpmath=sse -include-pch src/25a6634@@taisei@exe/taisei_pch.h.pch -MD -MQ 'src/25a6634@@taisei@exe/log.c.o' -MF 'src/25a6634@@taisei@exe/log.c.o.d' -o 'src/25a6634@@taisei@exe/log.c.o' -c ../taisei-v1.3/src/log.c
../taisei-v1.3/src/log.c:374:6: error: expected identifier or '('
        int fileno(FILE*);
            ^
/usr/include/stdio.h:406:20: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
                         ^
../taisei-v1.3/src/log.c:374:6: error: expected ')'
/usr/include/stdio.h:406:20: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
                         ^
../taisei-v1.3/src/log.c:374:6: note: to match this '('
/usr/include/stdio.h:406:19: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
                        ^
```

I have fixed the issue like this, but i'm not sure it won't mess up the build on other OSes (hence no PR):

```diff
Index: src/log.c
--- src/log.c.orig
+++ src/log.c
@@ -371,7 +371,9 @@ static bool output_supports_ansi_sequences(const SDL_R
 	}
 
 	int isatty(int);
+#ifndef fileno
 	int fileno(FILE*);
+#endif
 
 	return isatty(fileno(output->hidden.stdio.fp));
 }
```

Alternative solutions are welcome ^^

Charlène.

**Comment by Akaricchi** [comment]
Hello, and thanks for reporting.

The Right Thing™ here would be to somehow get `_POSIX_C_SOURCE >= 1` (or equivalent) defined before `stdio.h` is included, then we wouldn't need those declarations at all (broken headers notwithstanding). Unfortunately, this gets ugly with precompiled headers involved: you can't just define it inside the files making use of POSIX features, and you can't set file-specific compiler flags either (this can be hacked around by putting the file into a separate static library just for this purpose). I'm somewhat reluctant to define it globally, lest I accidentally use some non-standard feature.

So I'm not sure yet what'd be the nicest way to deal with this, but I'll definitely think of something and fix it for the next point release.

As for this workaround, I can see it potentially breaking something if `fileno` is defined as a simple identifier rather than a function-like macro. I would rather do away with the declarations entirely; using them at all was a lack of foresight on my end.

**Comment by julianaito** [comment]
Thanks, i'll do it that way then and am looking forward for the fix :)
