### ISSUE TITLE
Boss "halo" shader blocking out stage BG beyond its borders

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#239]
Discovered in playtesting on macOS, but could possibly affect other systems too. On AMD or Intel graphics, either with GL 3.3 or GL ES 3.0.

It's a weird "halo" that appears when the boss spawns in, even off-screen, blocking out the rest of the stage BG. Oddly, everything inside the halo seems to appear normally. It follows them when she comes into the arena, and disappears when the effect is turned off. Happens on all bosses that use this effect, from Stage 1 to the in-development EX boss.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/34408664/87962210-d4a07200-ca84-11ea-80ef-7d55a333820d.png">

**Comment by Akaricchi** [comment]
Finally caught this one today by accident. On my system this only seems to happen when `legacy_compat.glslh` is included, which happens when transpiling to a particularly old GLSL version (e.g. for GLES2). The `tanh` function is missing in legacy GLSL, so that header defines a shim:

```glsl
float tanh(float x) {
	float e2x = exp(2.0 * x);
	return (e2x - 1.0) / (e2x + 1.0);
}
```

This implementation has a rather poor input range.

However, I think we should still fix it in the shader, because the driver's `tanh` implementation may very well have similarly bad characteristics, and that's out of our control. We can use the legacy `tanh` shim as a baseline.
