### ISSUE TITLE
Extra buttons are seen as invalid and triggers an abort

### ISSUE THREAD

**Issue by lanodan** [taisei-project/taisei#331]
- Gentoo Linux
- SDL2 2.0.18
- Taisei 1.3.2 and 26b501249d327643474300adb54b681e716e402d
- Steam Controller (another gamepad with extra buttons should also work)

Steps:
1. Launch taisei
2. Press one of the extra buttons (ie. inner left/right)

Got:
```
1682      F: gamepad_button_state: Button id 17 is invalid
Aborted (core dumped) 
```

Expected: Extra button is ignored.

**Comment by Akaricchi** [comment]
I've just added support for the extra buttons in 4661c9609c016a0c6c54538c9875e01271e03ee6, so you should be able to actually map them now, but I haven't tested it since I don't have an appropriate device. I've also relaxed that error into a warning (a1142b1ffdaf62a43b4147b89c363bab984be148), but it should not happen anymore at all, unless SDL adds support for more buttons yet. The patches should be trivially backportable to the 1.3 branch as well. Let me know if this works for you.

**Comment by StarWitch** [comment]
I just tested before/after the new commit, and the fix works.

**Comment by lanodan** [comment]
Thanks for both, now it seems to be working fine.
