### ISSUE TITLE
Add Python to dependencies list in README

### ISSUE THREAD

**Issue by pzmarzly** [taisei-project/taisei#97]
I may be wrong, but I think CMakeLists.txt is set to require Python (which is later used only for Windows builds).

Also, while PACKAGE_DATA_LEANIFY is disabled by default, it would be nice to have this optional dependency mentioned in README.

**Comment by Akaricchi** [comment]
Python is optional. CMake just complains because it's a whiny crybaby. You are right though that it's only used for windows builds currently, so it's of little interest to most people. I probably should make it not look for python unless building for windows.

As for Leanify, that option probably should just be removed, because all assets in the repo are simply pre-leanified now.

For the record, we will most likely drop CMake and switch to Meson soon. @lachs0r has already started working on that in the [`meson`](/taisei-project/taisei/tree/meson) branch.
